apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://user123:pass123@postgres-user:5432/postgres
            - name: NODE_ENV
              value: production
          image: julpoz/wordle-user-service
          name: wordle-user-service
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
