services:
  gateway:
    build: ./gateway
    container_name: wordle-gateway
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      USER_SERVICE_URL: http://user-service:5001
      GAME_SERVICE_URL: http://game-service:5002
      JWT_SECRET: super-secret-key-change-in-production
    networks:
      - wordle-net

  frontend:
    build:
      context: ./wordle_frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: wordle-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - gateway
    networks:
      - wordle-net

  user-service:
    build: ./user-service
    container_name: wordle-user-service
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      POSTGRESQL_URI: postgres://user123:pass123@postgres-user:5432/postgres
      JWT_SECRET: super-secret-key-change-in-production
    depends_on:
      - postgres-user
    networks:
      - wordle-net

  game-service:
    build: ./game-service
    container_name: wordle-game-service
    ports:
      - "5002:5002"
    environment:
      MONGODB_URI: mongodb://mongo:27017/wordle
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379
      USER_SERVICE_URL: http://user-service:5001
    depends_on:
      - mongo
      - redis
    networks:
      - wordle-net

  postgres-user:
    image: postgres:15.13
    container_name: wordle-postgres-user
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - wordle-net

  mongo:
    image: mongo:6.0.13
    container_name: wordle-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - wordle-net

  redis:
    image: redis:7.0.15
    container_name: wordle-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wordle-net

volumes:
  mongo_data:
    name: wordle_mongo_data

  redis_data:
    name: wordle_redis_data

  postgres-user-data:
    name: wordle_postgres-user-data

networks:
  wordle-net:
    name: wordle_network
    driver: bridge