apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres-user
  name: postgres-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgres-user
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pass123
            - name: POSTGRES_USER
              value: user123
          image: postgres:15.13
          name: wordle-postgres-user
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-user-data
      restartPolicy: Always
      volumes:
        - name: postgres-user-data
          persistentVolumeClaim:
            claimName: postgres-user-data
