apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordle-persistent-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath # docker-desktop
  hostPath:
    path: /data