apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: game-service
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: game-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: game-service
    spec:
      containers:
        - env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/wordle
            - name: REDIS_HOST
              value: redis
          image: julpoz/wordle-game-service
          name: wordle-game-service
          ports:
            - containerPort: 5002
              protocol: TCP
      restartPolicy: Always
